-- MySQL Script generated by MySQL Workbench
-- Thu May  2 11:53:59 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema projeto_bdtss
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `users` (
  `id_users` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `username` VARCHAR(255) NOT NULL,
  `password_hash` VARCHAR(255) NOT NULL,
  `user_code` VARCHAR(8) NOT NULL,
  `date_creation` DATETIME NOT NULL DEFAULT  CURRENT_TIMESTAMP,
  `points` INT NOT NULL DEFAULT 0,
  `role` VARCHAR(60) NOT NULL DEFAULT 'user',
  PRIMARY KEY (`id_users`),
  UNIQUE INDEX `id_users_UNIQUE` (`id_users` ASC),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC),
  UNIQUE INDEX `user_code_UNIQUE` (`user_code` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `genres`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `genres` (
  `id_genres` INT NOT NULL AUTO_INCREMENT,
  `genre_name` VARCHAR(255) NOT NULL,
  `genre_photo` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_genres`),
  UNIQUE INDEX `id_genres_UNIQUE` (`id_genres` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `services`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `services` (
  `id_services` INT NOT NULL AUTO_INCREMENT,
  `services_name` VARCHAR(50) NOT NULL,
  `description` TEXT NOT NULL,
  `service_photo` VARCHAR(255) NOT NULL,
  `points_awarded` INT NOT NULL DEFAULT 0,
  `price` DECIMAL NOT NULL,
  `genres_id_genres` INT NOT NULL,
  PRIMARY KEY (`id_services`),
  UNIQUE INDEX `id_services_UNIQUE` (`id_services` ASC),
  INDEX `fk_services_genres1_idx` (`genres_id_genres` ASC),
  CONSTRAINT `fk_services_genres1`
    FOREIGN KEY (`genres_id_genres`)
    REFERENCES `genres` (`id_genres`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `liked_services`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `liked_services` (
  `users_id_users` INT NOT NULL,
  `services_id_services` INT NOT NULL,
  `date_completed` DATETIME NULL DEFAULT  CURRENT_TIMESTAMP,
  PRIMARY KEY (`users_id_users`, `services_id_services`),
  INDEX `fk_users_has_services_services1_idx` (`services_id_services` ASC),
  INDEX `fk_users_has_services_users1_idx` (`users_id_users` ASC),
  CONSTRAINT `fk_users_has_services_users1`
    FOREIGN KEY (`users_id_users`)
    REFERENCES `users` (`id_users`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_has_services_services1`
    FOREIGN KEY (`services_id_services`)
    REFERENCES `services` (`id_services`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
